import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/tree-shaking', 'guides/migration'],
		},
		{
			type: 'category',
			label: 'Recipes',
			// Pinned to the index so the category label itself is a landing page,
			// and so index is not repeated inside the list below.
			link: { type: 'doc', id: 'recipes/index' },
			items: [
				'recipes/format-date-for-locale',
				'recipes/debounce-a-search-input',
				'recipes/parse-untrusted-json',
				'recipes/generate-a-unique-slug',
				'recipes/retry-with-exponential-backoff',
			],
		},
		{
			type: 'category',
			label: 'CLI',
			items: ['guides/cli'],
		},
		{
			type: 'category',
			label: 'Modules',
			items: [
				{
					type: 'autogenerated',
					dirName: 'modules',
				},
			],
		},
		{
			type: 'category',
			label: 'API Reference',
			// Pinning api/index as the category's doc link does two things:
			//  1. Clicking "API Reference" navigates to the index landing page.
			//  2. Docusaurus auto-excludes api/index from the autogenerated
			//     children, so the list starts at abortController instead of
			//     showing "@rtorcato/js-common" between i18n and json.
			link: { type: 'doc', id: 'api/index' },
			items: [
				{
					type: 'autogenerated',
					dirName: 'api',
				},
			],
		},
		{
			type: 'category',
			label: 'Releases',
			items: ['changelog'],
		},
	],
}

export default sidebars
