import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	docs: [
		{
			type: 'category',
			label: 'Start here',
			collapsed: false,
			items: ['index', 'guides/installation', 'guides/quick-start', 'guides/migration'],
		},
		{
			type: 'category',
			label: 'CLI',
			items: ['guides/cli'],
		},
		{
			type: 'category',
			label: 'Modules',
			items: [
				{
					type: 'autogenerated',
					dirName: 'modules',
				},
			],
		},
		{
			type: 'category',
			label: 'API Reference',
			items: [
				{
					type: 'autogenerated',
					dirName: 'api',
				},
			],
		},
	],
}

export default sidebars
